SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
 TYPE NAMEARRAYS IS VARRAY(5) OF VARCHAR2(10);
 TYPE GRADES IS VARRAY(5) OF INTEGER;
 NAMES NAMEARRAYS;
 MARKS GRADES;
 
 BEGIN
 NAMES:=NAMEARRAYS('A','B','C','D');
 MARKS:=GRADES(98,78,91,87);
 FOR i IN 1..(NAMES.COUNT) LOOP
	dbms_output.put_line('Names: '|| NAMES(i)||' '||'MARKS: ' || MARKS(i));
 END LOOP;
 end;
 /